# Generated by Django 5.1.4 on 2025-01-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_food_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='restaurant',
        ),
    ]
